name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 9af989289d54d7dafbd87d6a68f18e1a
          TIMEZONE: Asia/Seoul
          ALL_COMMITS: true
          
